added img for no vacancy responses
PROCOLLAB-github/procollab pull request #100
Opened 2023-08-26 15:37 UTC by cloudsurf5

2023-08-26 15:38 UTC, gregor-tokarev commented
Task linked: [CU-862kag04p Картинка на отсутствие откликов](https://app.clickup.com/t/862kag04p)

2023-08-29 13:22 UTC, gregor-tokarev requested changes

2023-08-29 13:22 UTC, gregor-tokarev commented on src/app/office/projects/detail/responses/responses.component.scss
> +      color: var(--dark-grey);
The color is right. But it's not specified in figma, write comment in figma and tag Polina to resolve it

2023-08-30 10:10 UTC, TThanos3000 approved these changes

2023-08-30 10:11 UTC, TThanos3000 approved these changes

2023-08-30 17:54 UTC, gregor-tokarev approved these changes

2023-08-30 17:55 UTC, merged