Dadrozdov101 pro 154
PROCOLLAB-github/procollab pull request #175
Opened 2024-02-26 19:22 UTC by cloudsurf5

2024-02-28 06:00 UTC, gregor-tokarev requested changes
Фикси, потом еще итерацию сделаем, очень большой мр получился

2024-02-29 14:16 UTC, cloudsurf5 commented on src/app/office/program/program.routes.ts
> +  },
по логике должно лежать в detail, но фактически в роутере нужно на уровень вверх выносить, потому что там идет отдельный nav bar для оценок

2024-02-29 14:24 UTC, cloudsurf5 commented on src/app/office/program/shared/rating-card/rating-card.component.html
> +      </div>
по идее да, только вот куда ее именно

2024-02-29 14:59 UTC, cloudsurf5 commented on src/app/office/program/shared/rating-card/rating-card.component.scss
> +      display: -webkit-box;
это стили для скрытия объемного описания проекта, чтобы была возможность развернуть/свернуть описание

2024-03-04 13:48 UTC, gregor-tokarev approved these changes

2024-03-04 13:55 UTC, merged