Dadrozdov101 pro 94
PROCOLLAB-github/procollab pull request #179
Opened 2024-03-10 16:38 UTC by cloudsurf5

2024-03-12 14:54 UTC, gregor-tokarev requested changes

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/onboarding/onboarding.component.scss
> +  }
обзови nav & img классами

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-one/stage-one.component.scss
> +  }
классы

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-one/stage-one.component.scss
> +  }
класс

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-one/stage-one.component.scss
> +    }
классы!

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-one/stage-one.component.ts
> +    speciality: this.nnFb.control("", Validators.required),
["", [...]] - с NonNullable можно такой синтаксис заюзать?

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-three/stage-three.component.ts
> +  userRole!: number;
! => ? может где-нибудь дернуться до субскрайба в онините, лучше судьбу не испытывать

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-three/stage-three.component.ts
> +    this.stageSubmitting = true;
А где ты false обратно проставляешь?

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-two/stage-two.component.scss
>      }
харам, сделай классом

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-two/stage-two.component.scss
>      }
классы

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-two/stage-two.component.scss
> +    }
классом

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-two/stage-two.component.scss
> +      cursor: pointer;
классы

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/onboarding/stage-two/stage-two.component.ts
Везде где getRawValue() переделай на type-safe аналоги

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/shared/skills-basket/skills-basket.component.scss
> +    }
классом

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/shared/skills-group/skills-group.component.scss
> +    }
классом

2024-03-12 14:54 UTC, gregor-tokarev commented on src/app/office/shared/skills-group/skills-group.component.scss
> +      }
классом

2024-03-13 13:34 UTC, cloudsurf5 commented on src/app/office/onboarding/stage-three/stage-three.component.ts
> +  userRole!: number;
а тут я не менял ничего, просто компонент переименовал

2024-03-13 13:34 UTC, cloudsurf5 commented on src/app/office/onboarding/stage-three/stage-three.component.ts
> +    this.stageSubmitting = true;
не менял файл, просто переименовал

2024-03-13 14:48 UTC, cloudsurf5 commented on src/app/office/onboarding/stage-two/stage-two.component.ts
не совсем понял, разве rawValue не type-safe?

2024-03-14 13:30 UTC, gregor-tokarev approved these changes

2024-03-14 15:44 UTC, merged