Rewrite bar styles to bar component
PROCOLLAB-github/procollab pull request #194
Opened 2024-06-01 09:31 UTC by Awakich

2024-06-04 13:07 UTC, gregor-tokarev requested changes

2024-06-04 13:07 UTC, gregor-tokarev commented on projects/social_platform/src/app/ui/components/bar/bar.component.html
просто link а не links[$index] здесь

2024-06-04 13:07 UTC, gregor-tokarev commented on projects/social_platform/src/app/ui/components/bar/bar.component.ts
Зачем ngOnInit?

2024-06-04 13:07 UTC, gregor-tokarev commented on projects/social_platform/src/styles/components/_bar.scss
А зачем здесь это остается?

2024-06-04 14:43 UTC, Awakich commented on projects/social_platform/src/styles/components/_bar.scss
Перенес в компонент

2024-06-06 14:53 UTC, gregor-tokarev approved these changes

2024-06-08 09:12 UTC, merged