add subscription page and subscription modals
PROCOLLAB-github/procollab pull request #196
Opened 2024-06-10 17:10 UTC by Awakich

2024-06-11 04:29 UTC, gregor-tokarev requested changes
![image](https://github.com/PROCOLLAB-github/procollab/assets/52395572/f0662fb9-6b28-4773-b6f6-0dcf2da64d59)

currentColor в иконке не прописал
вот так:
<img width="1152" alt="image" src="https://github.com/PROCOLLAB-github/procollab/assets/52395572/9f2129ce-476a-4931-aff7-ddbd8ff31678">

2024-06-11 04:29 UTC, gregor-tokarev commented on projects/skills/src/app/app.routes.ts
тут молодцом

2024-06-11 04:29 UTC, gregor-tokarev commented on projects/skills/src/app/subscription/subscription-modal/subscription-modal.component.scss
Есть у нас модалка уже переюзай ее, если она в основе осталась то перенеси в модуль ui

2024-06-11 04:29 UTC, gregor-tokarev commented on projects/skills/src/app/subscription/subscription-modal/subscription-modal.component.ts
> +  @Input() checked!: boolean;
@Input({required: true})

2024-06-11 09:45 UTC, Awakich commented on projects/skills/src/app/subscription/subscription-modal/subscription-modal.component.scss
modal в ui находиться, переиспользовал этот компонент

2024-06-12 04:44 UTC, gregor-tokarev approved these changes

2024-06-12 04:54 UTC, merged