add edit route
PROCOLLAB-github/procollab pull request #202
Opened 2024-07-16 12:29 UTC by Awakich

2024-07-17 05:07 UTC, gregor-tokarev requested changes
![image](https://github.com/user-attachments/assets/5a8e4a1e-02d7-4591-9f3b-4c0fda8f677f)

1) Не меняется step при навигации
2) что за ';'?

2024-07-17 05:07 UTC, gregor-tokarev commented on projects/social_platform/src/app/office/projects/detail/info/info.component.html
> +        <a [routerLink]="['/office/projects/', project.id, 'edit', { editingStep: 'team' }]">
queryParams не так добавляются

2024-07-17 05:07 UTC, gregor-tokarev commented on projects/social_platform/src/app/office/projects/edit/edit.component.ts
> +    this.editingStep = this.route.snapshot.paramMap.get('editingStep') as 'team' | 'main' | 'achievements' || 'main';
Ты перепутал queryParams которые поле ? идут
и обычные params

2024-07-17 06:58 UTC, Awakich commented on projects/social_platform/src/app/office/projects/edit/edit.component.ts
> +    this.editingStep = this.route.snapshot.paramMap.get('editingStep') as 'team' | 'main' | 'achievements' || 'main';
поменял на queryParams и добавил отлов editingStep

2024-07-18 06:26 UTC, gregor-tokarev requested changes
![image](https://github.com/user-attachments/assets/55950019-3c12-4bfa-a476-5a6152cf1782)


Отображается какая-то v

+ у меня нет кнопки добавить вакансию

2024-07-18 10:02 UTC, gregor-tokarev approved these changes

2024-07-18 10:03 UTC, merged